name: style-check
on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Google Java Format
        # uses: axel-op/googlejavaformat-action@5045c8c244a22eb6a28eeb6050cc2baebd75c5f2
        uses: axel-op/googlejavaformat-action@v3.4.0
        with:
          # Arguments for the Google Java Format executable
          args: 
          skipCommit: true
